language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "oliverhruby-github"
    token:
      secure: ${SONAR_TOKEN}
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run e2e
  - npm run build
  - sonar-scanner
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
